name: CI

on:
  push:
    branches-ignore:
      - 'master'

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Java Set-Up
        uses: actions/setup-java@v2

        with:
          distribution: "adopt"
          java-version: "8"

      - name: Set up secrets
        run: 'echo "$NPM_AUTH" >> ~/.npmrc'

        env:
          NPM_AUTH: ${{secrets.NPM_AUTH}}

      - name: NodeJS Set-Up
        run: yarn install --save

      - name: Gradle Build
        run: /bin/sh ./gradlew build
